### ISSUE TITLE
prompt_general.yami

### ISSUE THREAD

**Issue by coding1028** [coding1028/AI_RAG_with_streamlit#5]
# general.yami

pages에 있는 .py들을 작성할 때, Import하였던 yaml파일 중 하나이다.

제일 평범한 프롬프트 코드이다.
```yaml
_type: "prompt"
template: |
  당신은 친절한 AI 어시스턴트입니다. 사용자의 요청사항에 따라 적절한 답변을 제공해주세요.

  #Question:
  {question}
  
input_variables: ["question"]


```
